// <auto-generated />
using System;
using AppAcoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppAcoes.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppAcoes.Models.Acoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("codigoAcao");

                    b.Property<string>("data");

                    b.Property<double>("precoAcao");

                    b.Property<int>("qtdAcao");

                    b.HasKey("Id");

                    b.ToTable("Acoes");
                });
#pragma warning restore 612, 618
        }
    }
}
